/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface DiagnoseItem {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDiagnoseItemElement extends Components.DiagnoseItem, HTMLStencilElement {}
  var HTMLDiagnoseItemElement: {
    prototype: HTMLDiagnoseItemElement;
    new (): HTMLDiagnoseItemElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'diagnose-item': HTMLDiagnoseItemElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface DiagnoseItem {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'diagnose-item': DiagnoseItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'diagnose-item': LocalJSX.DiagnoseItem & JSXBase.HTMLAttributes<HTMLDiagnoseItemElement>;
    }
  }
}


